### ISSUE TITLE
Altis: Notif System errors

### ISSUE THREAD

**Issue by CarterJWard** [LarryLancelot/ExileGaming#14]
error displayed in rpt on launch
---
Error in expression <_display = finddisplay 46;
if (GVAR_PNAS["de100_notify",true]) then {
if (_error>
  Error position: <["de100_notify",true]) then {
if (_error>
  Error Missing )
File mpmissions\Altis_Life.Altis\core\functions\fn_notification_system.sqf, line 20

**Comment by fresqo** [comment]
if (GVAR_PNAS["de100_notify",true]) then {
 if (_error) then {
 playSound "3DEN_notificationWarning";
 } else {
 playSound "HintExpand";
 };
}; 

GVAR_PNAS is not a macro.. 
and the variable its searching for is never set at all.. so its never gonna result false.. always true.. so can remove the if statment and var.

**Comment by ITSJORDAN-TFA** [comment]
No longer using that system!
