### ISSUE TITLE
Proficency updates

### ISSUE THREAD

**Issue by CarterJWard** [LarryLancelot/ExileGaming#15]
TO DO:
- [x] Check type of resouce
- [x] get type level
- [x] decide amount based on level
- [x] add xp
- [ ] Add profs to config_prof
- [ ] TEST/debug

**Comment by CarterJWard** [comment]
why is _prof private on line 18 in life_server/functions/mysql/fn_updateRequest?

**Comment by ITSJORDAN-TFA** [comment]
It is just the defining of the var, like the ones in the private array on the first line, it allows it to be different vars at different times. 
https://community.bistudio.com/wiki/private

**Comment by CarterJWard** [comment]
Proficiency finally fixed with #20
