### ISSUE TITLE
Tanoa: Military Login issues

### ISSUE THREAD

**Issue by CarterJWard** [LarryLancelot/ExileGaming#16]
23:12:48 Error in expression <) select 0),((_x select 1) select 1)]]} forEach ((_this select 11));
};
};

case>
23:12:48   Error position: <forEach ((_this select 11));
};
};

case>
23:12:48   Error foreach: Type String, expected Array
23:12:48 File core\session\fn_requestReceived.sqf [SOCK_fnc_requestReceived], line 142

**Comment by fresqo** [comment]
what does the database look like? are you sure its saving stats at all? have you set the datatype properly?

**Comment by CarterJWard** [comment]
Server was using incorrect database. Issue resolved.
