### ISSUE TITLE
Tanoa : Hideout Processing 

### ISSUE THREAD

**Issue by CarterJWard** [LarryLancelot/ExileGaming#2]
Hideout processing does not work in heroin and cocian basin's 
Possible issues/resolutions : 
Wrong add action code on flag and basin (Based of client side RPT logs),
Incorrect Item names on processing config

RPT Errors:
-------------------------------------------------------------------------------------------------
 Error in expression <[_pos select 0, _pos select 1, _pos sele>
18:45:56   Error position: <[_pos select 0, _pos select 1, _pos sele>
18:45:56   Error Type String, expected Bool
18:49:06 Error in expression <er,_hideoutObjs,25]) select 0;
_group = _hideout getVariable ["gangOwner",grpNul>
18:49:06   Error position: <_hideout getVariable ["gangOwner",grpNul>
18:49:06   Error Undefined variable in expression: _hideout
18:49:06 File mpmissions\__CUR_MP.Tanoa\core\actions\fn_captureHideout.sqf, line 14
18:49:07 Error in expression <= _ui displayCtrl 38202;
};
_cP = _cP + _cpRate;
_progressBar progressSetPositio>
18:49:07   Error position: <_cpRate;
_progressBar progressSetPositio>
18:49:07   Error Undefined variable in expression: _cprate
18:49:07 File mpmissions\__CUR_MP.Tanoa\core\actions\fn_captureHideout.sqf, line 60
18:49:07 Error in expression <eText = _ui displayCtrl 38202;
};
_cP = _cP + _cpRate;
_progressBar progressSetP>
18:49:07   Error position: <_cP + _cpRate;
_progressBar progressSetP>
18:49:07   Error Undefined variable in expression: _cp
--------------------------------------------------------------------------------------------------

This continues to spam infinite erros on client side rpt's

**Comment by fresqo** [comment]
```
_altisArray = ["Land_u_Barracks_V2_F","Land_i_Barracks_V2_F"];
_tanoaArray = ["Land_House_Small_01_F", "Land_House_Small_03_F"];
private _hideoutObjs = ALTIS_TANOA(_altisArray,_tanoaArray);
_hideout = (nearestObjects[getPosATL player,_hideoutObjs,25]) select 0;
```
this is the issue, the fact that none of the tanoa buildings used for hideouts are within 25 metres of the player when capturing. move the flag closer or up the range

**Comment by CarterJWard** [comment]
@fresqo correct buildings are in the capture action and rpt's are no longer producing producing these errors however. the processing basin in the cocaine and heroin hideouts do not work. Have tried to changing the init for the basins for the weed processing basin. 

This is the only error being produced on client rpt's (error is produced right after server initialization )
------------------------------------------------------------------------------------------------
18:14:03 Error in expression <[_pos select 0, _pos select 1, _pos sele>
18:14:03   Error position: <[_pos select 0, _pos select 1, _pos sele>
18:14:03   Error Type String, expected Bool
------------------------------------------------------------------------------------------------
