### ISSUE TITLE
Tanoa: Load dead gear

### ISSUE THREAD

**Issue by CarterJWard** [LarryLancelot/ExileGaming#23]
Error 👍
16:34:00 Error in expression <_loadout select 0;
_launcher = _loadout select 1;
_handgun = _loadout select 2;
>
16:34:00   Error position: <select 1;
_handgun = _loadout select 2;
>
16:34:00   Error Zero divisor
16:34:00 File core\functions\fn_loadDeadGear.sqf [life_fnc_loadDeadGear], line 91

When a player is revived they stripped but they are not given their stuff back.

**Comment by Nolan105** [comment]
Iv Asked for frez to hop on have a look :)

**Comment by fresqo** [comment]
Please specify which server this is on

**Comment by CarterJWard** [comment]
@fresqo this is for tanoa. Sorry slipped my mind because it's the only server is active development rn

**Comment by fresqo** [comment]
is there any more in the RPT logs? before that error..

**Comment by CarterJWard** [comment]
@fresqo no this is the only error the is produced.

**Comment by fresqo** [comment]
GEAR LOSS FROM REVIVE (FIX) #26
Please upload and test.

**Comment by fresqo** [comment]
Let me know how it goes
