### ISSUE TITLE
Gear Removal On death.

### ISSUE THREAD

**Issue by CarterJWard** [LarryLancelot/ExileGaming#27]
When a player is killed and they respawn. They do not lose their c vItems but the player weight get's set back to 0. 

Current investigations show no error's in RPT. Will continue investigations tonight.

**Comment by fresqo** [comment]
Wasn't this sorted? Does the money go to zero also?

**Comment by Nolan105** [comment]
i died and i still had money on the respawn

**Comment by CarterJWard** [comment]
@fresqo only on some occasions money gets set back to 0. Still no error in rpt's

**Comment by fresqo** [comment]
how are people respawning? admin menu? or waiting time ? or medic?

**Comment by CarterJWard** [comment]
@fresqo we have gone through every method of respawning and they still keep their virt inventory and sometimes cash. I added diag_log to the top of fn_dropItems and its not even being called.

**Comment by fresqo** [comment]
Please see commit 9915d07 .. amazing the server didn't implode with that mess lol

**Comment by CarterJWard** [comment]
Vitems now drop and can be picked up, Thankyou fresqo.
